Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -26,16 +26,20 @@ jobs:
         run: |
           # Get the JSON input from the previous step
           input_json="${{ steps.read_json.outputs.json_content }}"
-          
-          # Loop through the IDs and generate the CSS rules
-          output_css=""
-          for id in $(echo "${input_json}" | jq -r '.ids[]'); do
-            output_css="${output_css}[href*=\"${id}\"], {filter:blur(20px)!important;clip-path:circle(50%)}\n"
-          done
-            output_css=output_css + "zzz\n{filter:blur(20px)!important;clip-path:circle(50%)}\n"
+
+          # Check if the input_json is empty (no content in ids.json)
+          if [ -z "$input_json" ]; then
+            echo "Error: JSON input is empty."
+            exit 1
+          fi
           
           # Save the output CSS to a file
-          echo -e "${output_css}" > converted_styles.css
+          echo -n "" > converted_styles.css
+
+          # Loop through the IDs and generate the CSS rules
+          for id in $(echo "${input_json}" | jq -r '.ids[]'); do
+            echo -e "[href*=\"${id}\"] {\n  /* Your CSS rules for ID ${id} */\n}\n" >> converted_styles.css
+          done
 
       - name: Commit changes
         run: |
